name: Search engine client
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt;
    - name: Test with unittest
      run: |
        python -m unittest discover -s unit_tests
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: get image tag
      id: gettags
      run: |
        if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
          TAGS='["openmicroscopy/searchengineclient:latest","openmicroscopy/searchengineclient:'${GITHUB_REF/refs\/tags\//}'"]'
        else
          TAGS='["openmicroscopy/searchengineclient:latest"]'
        fi
        echo '::set-output name=tags::'$TAGS
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./deployment/docker/centos/Dockerfile
        push: false
        #tag will be changed later to and it should have its
        #tags: openmicroscopy/searchengineclient:0.1.0
        tags: ${{ join(fromJson(steps.gettags.outputs.tags)) }}

